### ISSUE TITLE
[로그인] - 카카오 로그인 API부분 작성 중 firebase API단 구현 질문

### ISSUE THREAD

**Issue by tilto0822** [2022-dimipay-recruit/Flutter-Server#1]
위치는 develop 브랜치의 /src/routes/LoginRouter.ts의 constructor아래의 함수 보시면 될거에요.

1. 클라이언트에서 보내는 요청 구조가 어떻게 되나요...? 카카오 로그인이면 access_token만 body에 넣어 보내주나요?

2. 아래부분 빨간줄을 보면, 주석 밑의 updateParams에 photoURL이 없어서 그런데, 이걸 어떻게 해결해야 firebase 구조하고 맞나요?
![image](https://user-images.githubusercontent.com/56160437/174066384-7de85535-239f-44a6-81a4-4b6b91aa5b02.png)

3. 궁극적으로, 해당 post요청이 실행되었을 때 client에서는 어떻게 응답을 받아야 하나요? (어떤 내용이 포함된 상태로 반환되어야 하나요?)
![image](https://user-images.githubusercontent.com/56160437/174066478-a4b0df9d-9e05-402d-aafa-41c161bde700.png)

**Comment by doch2** [comment]
1. 네네 맞습니다! AccessToken만 데이터로 넣어서 요청 보내요. 아래 코드는 달그락에서 사용되었던 API 요청 코드니까 보시면 요청보낼 떄 날리는 데이터 값 이해가실거에요!
![image](https://user-images.githubusercontent.com/30923566/174075530-0e466e7d-69ef-4f17-9386-ff5fabec895b.png)

2. 제가 기억하기로 저기에 있는 updataParam은 Firebase Auth에 등록하는 유저 정보일거에요. 달그락에서 profileImg는 Firestore Database 유저 정보란에 따로 저장했었어요.
3. Client에서는 Firebase Auth로 로그인 하기 위한 Firebase의 CustomToken을 응답으로 받아야 합니다.

**Comment by tilto0822** [comment]
2. 그러면, profileImg가 있다면 링크를 넣고, 없다면 null을 넣고 진행해도 괜찮을까요?
3. 요건 지금 customToken이 나오는거하고 userRecord가 나오는 로직이 두개가 있어서, userRecord를 customToken으로 뽑아낼 수 있는 방법을 찾아볼게요

**Comment by doch2** [comment]
네네 어.. 아마 없으면 그냥 빈 문자열 출력되서 나오는걸로 알고있긴한데, 없어도 그냥 null 말고 빈 문자열로 반환해주세요!

방법 찾아주시면 여기다가 코멘트 남겨주세요 :)

**Comment by tilto0822** [comment]
해결했습니다~
노션 문제해결 보고서 링크 첨부해요!

[문제해결 보고서](https://dohui-ryu-page.notion.site/2022-05-27-2022-06-19-API-7dfa5dbd133547e6be426b8c105bdbd6)
